/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Post from 'src/components/Post/Post';

const TypeQuest = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `896px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  overflow: `hidden`,
});

const Post1 = styled(Post)(({ theme }) => ({
  width: `414px`,
  height: `700px`,
  margin: `0px`,
}));

function MsgApp1(props) {
  return (
    <TypeQuest className={props.className}>
      <Post1 />
    </TypeQuest>
  );
}

export default MsgApp1;
