/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import PlusImage from 'src/assets/images/MsgApp1_plus.png';
import { styled } from '@mui/material/styles';
import Post from 'src/components/Post/Post';

const TypeQuest = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  height: 'auto',
});

const GridFrame = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `grid`,
  position: `relative`,
  isolation: `isolate`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
  height: `auto`,
  gridTemplateColumns: `repeat(auto-fit, minmax(414px, 1fr))`,
  columnGap: `10px`,
  rowGap: `10px`,
  width: `100%`,
});

const Post1 = styled(Post)(({ theme }) => ({
  width: `414px`,
  height: `700px`,
  margin: `0px`,
}));

const NewButton = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.2)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `sticky`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `148px`,
  width: `414px`,
  margin: `10px 0px 0px 0px`,
  bottom: `0`,
  zIndex: `3000`,
});

const Plus = styled('img')({
  height: `128px`,
  width: `128px`,
  position: `absolute`,
  left: `276px`,
  top: `10px`,
});

function MsgApp1(props) {
  return (
    <TypeQuest className={props.className}>
      <GridFrame>
        {props.posts &&
          props.posts.map((mypost, index) => {
            return <Post1 key={index} post={props.posts[index]} />;
          })}
      </GridFrame>
      <NewButton>
        <Plus src={PlusImage} loading="lazy" alt={'plus'} />
      </NewButton>
    </TypeQuest>
  );
}

export default MsgApp1;
