/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import XImage from 'src/assets/images/StandaloneImage_x.png';
import { styled } from '@mui/material/styles';
import useStandaloneImage from 'src/components/StandaloneImage/useStandaloneImage';

const StandaloneImage1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `936px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `20px`,
  boxSizing: `border-box`,
});

const Image1 = styled('div', {
  shouldForwardProp: (prop) => !['props'].includes(prop.toString()),
})(({ props }) => ({
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `896px`,
  width: `414px`,
  margin: `0px`,
  overflow: `hidden`,
  backgroundImage: props.post.image,
}));

const Close = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.2)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `10px`,
  boxSizing: `border-box`,
  left: `264px`,
  top: `20px`,
  cursor: `pointer`,
});

const X = styled('img')({
  height: `107.25px`,
  width: `105.02px`,
  margin: `0px`,
});

function StandaloneImage(props) {
  const { fns } = useStandaloneImage(props);

  return (
    <StandaloneImage1 className={props.className}>
      <Image1 props={props}>
        <Close onClick={fns.handleCloseButtonClick}>
          <X src={XImage} loading="lazy" alt={'x'} />
        </Close>
      </Image1>
    </StandaloneImage1>
  );
}

export default StandaloneImage;
